/**
 * The page's words in each language (English, Russian, Latvian, Finnish):
 * so far the login page's, the settings page's, the lobby's and the game's
 * buttons. Each is about as long as the English, so the page keeps its
 * shape (the buttons' words were measured to keep the phone's rows as the
 * English has them); `{…}` is filled in. A word that goes with a count has
 * a form for each of the language's plural kinds (`Intl.PluralRules`:
 * Russian's one, few, many, other; Latvian's zero, one, other; English and
 * Finnish one, other), picked by `{n}`.
 *
 * Static texts in index.html say which word they are with `data-word`, and
 * their tooltips and labels with `data-word-title` and `data-word-label`
 * (`translate`); the lobby's How to play and About are written out in each
 * language there instead, as they hold links.
 */

export const WORDS = {
  en: {
    // The login page and the settings page.
    name: 'Your name',
    namePlaceholder: 'Visible name ({max})',
    language: 'Language',
    auto: 'Auto',
    badName: 'Use 1–{max} letters or digits. Spaces and - _ . \' may go between them.',
    refused: 'The server said no ({why}).',
    offline: 'Could not reach the game server.',
    // The login page.
    play: 'Play',
    loading: 'Loading the question…',
    question: 'What is {sum}?',
    noQuestion: 'Could not load the question. Press Play to try again.',
    wrongAnswer: 'That’s not it. Try this one.',
    // The settings page.
    settings: 'Settings',
    back: 'Back',
    save: 'Save',
    // The lobby.
    playingAs: 'Playing as',
    mode: 'Mode',
    players: 'Players',
    newGame: 'New game',
    coopChoice: 'Cooperation: together against the Dark Lord',
    easyChoice: 'Easy Lord: together against a weaker Dark Lord',
    veryEasyChoice: 'Very Easy Lord: as Shared Easy Lord, and units breed twice as fast',
    sharedChoice: 'Shared Easy Lord: one stock for all, against a weaker Dark Lord',
    ffaChoice: 'Free for all: each against the other',
    yourGames: 'Your games',
    yourGamesNone: 'None yet. Start one, or join one below.',
    waitingGames: 'Waiting for a player',
    waitingGamesNone: 'No one is waiting right now.',
    ongoingGames: 'Ongoing',
    ongoingGamesNone: 'Nobody else is playing right now.',
    finishedGames: 'Recently finished',
    finishedGamesNone: 'No game has ended yet.',
    howToPlay: 'How to play',
    about: 'About',
    open: 'Open',
    join: 'Join',
    watch: 'Watch',
    scores: 'Scores',
    delete: 'Delete',
    leave: 'Leave',
    deleteTitle: 'Delete it for good: nobody else plays it',
    leaveTitle: 'Give up your seat, for someone else to take',
    askDelete: 'Delete “{game}” for good?',
    askLeave: 'Leave “{game}”? Your seat goes to whoever comes next.',
    deleted: 'Deleted “{game}”.',
    left: 'Left “{game}”.',
    notDeleted: 'Could not delete “{game}” ({why}).',
    notLeft: 'Could not leave “{game}” ({why}).',
    notStarted: 'Could not start a game ({why}).',
    noSuchGame: 'There is no game at that address.',
    notOpened: 'Could not open that game.',
    aGame: 'A game',
    tooMany: 'You have {reasons}. Go back to one of them, or clear one, before starting another:',
    tooManyWaiting: { one: '{n} game of yours waiting for a player', other: '{n} games of yours waiting for a player' },
    tooManySeated: { one: 'a seat in {n} game under way', other: 'a seat in {n} games under way' },
    and: ', and ',
    // A game's mode, by its key in MODES, and how a finished one came out.
    coop: 'Cooperation',
    easy: 'Easy Lord',
    veryEasy: 'Very Easy Lord',
    shared: 'Shared Easy Lord',
    ffa: 'Free for all',
    nobodyWon: 'over, nobody won',
    won: 'won',
    lordWon: 'the Dark Lord won',
    sideWon: '{side} won',
    // The players' sides, by their names in SIDES.
    blue: 'Blue',
    crimson: 'Crimson',
    green: 'Green',
    gold: 'Gold',
    teal: 'Teal',
    orange: 'Orange',
    rose: 'Rose',
    silver: 'Silver',
    azure: 'Azure',
    lime: 'Lime',
    indigo: 'Indigo',
    cherry: 'Cherry',
    olive: 'Olive',
    coral: 'Coral',
    white: 'White',
    mint: 'Mint',
    // The game's buttons. A building's is its name and price ("Tower · 60").
    groupBuild: 'Build',
    groupSelected: 'Selected',
    groupView: 'View',
    tower: 'Tower',
    wagon: 'Wagon',
    pit: 'Pit',
    farm: 'Farm',
    band: 'Band',
    upgrade: 'Upgrade',
    crew: 'Crew…',
    heroes: 'Heroes…',
    return: 'Return',
    abort: 'Abort',
    attack: 'Attack…',
    recenter: 'Recenter',
    mute: 'Mute',
    coordinates: 'Coordinates',
    releaseSeat: 'Release',
    takeSeat: 'Take seat',
    newBase: 'New base',
    newBaseTitle: 'Your castle fell: play on with a free one, the one selected if it is free',
    startNow: 'Start',
    goOn: 'Go on',
    startNowTitle: 'Start without the players missing: the Dark Lord leaves their castles be until they are back',
    lobby: 'Lobby',
    zoomOut: 'Zoom out',
    zoomIn: 'Zoom in',
    buildTitle: '{name} ({key}): {price}',
    stoneCost: { one: '{n} stone', other: '{n} stone' },
    metalCost: '{n} dark metal, near your castle',
    hungerCost: '{n}% more hunger (free once it is 100%)',
    free: 'free',
    upgradeTitle: 'Upgrade (U)',
    crewTitle: 'Choose who works here (C)',
    heroesTitle: 'Your heroes, highest level first (H)',
    abortTitle: 'Give up a building still going up: its crew goes home, and its cost is lost',
    attackTitle: 'Attack (A)',
    muteTitle: 'Sounds are on unless this is pressed; your choice is kept in this browser',
    // The arrows that fold the status panel and hide the minimap.
    statusFold: 'Hide the game\'s details',
    statusUnfold: 'Show the game\'s details',
    minimapHide: 'Hide the minimap (M)',
    minimapShow: 'Show the minimap (M)',
    // The status panel.
    masthead: 'Vigame · prototype',
    statusGame: 'Game',
    statusTime: 'Time',
    statusYou: 'You',
    statusUnits: 'Units',
    statusTile: 'Tile',
    statusObservers: 'Observers',
    renameTitle: 'Rename the game',
    playersTitle: 'Seated players here, of the game\'s seats; it blinks while the game waits for the rest',
    paused: 'paused',
    pausedTitle: 'The game waits until every player is here',
    overYouWon: 'over: you won',
    overYouLost: 'over: you lost',
    overSideWon: 'over: {side} won',
    spectator: 'Spectator',
    awayCount: '{n} away',
    offlineShort: 'offline',
    grass: 'Grass',
    meadow: 'Meadow',
    scrub: 'Scrub',
    water: 'Water',
    impassable: 'impassable',
    noBuilding: 'no building',
    darkLord: 'Dark Lord',
    raiders: 'Raiders',
    // The stock and selection panel; a building's lines.
    stone: 'Stone',
    darkMetal: 'Dark metal',
    food: 'Food',
    teamStone: 'Team stone',
    teamDarkMetal: 'Team metal',
    teamFood: 'Team food',
    hungerShort: 'hunger {n}%',
    stoneTitle: 'In bold from 60, enough for a tower',
    metalTitle: 'In bold from 30, enough for a wagon\'s upgrade',
    foodCountTitle: 'In bold when the store, with what the castle and farms give by then, won\'t feed every unit a full next meal',
    foodStoreTitle: 'The most the store holds',
    nothingSelected: 'Nothing selected',
    minimapLabel: 'Map of the whole board: press or drag on it to look there',
    castle: 'Castle',
    lair: 'Lair',
    ghoul: 'Ghoul',
    ogre: 'Ogre',
    raider: 'Raider',
    graded: '{name} (grade {n})',
    atHome: '{n}/{max} at home',
    nextUnit: 'next unit {done}',
    crewLine: 'crew {n}/{max}',
    levelLine: 'level {n}',
    upgrading: 'upgrading {done}',
    goingUp: 'going up {done}',
    dugOut: 'dug out',
    depthLine: 'depth {n}/{max}, {stone}',
    nextFood: 'next food {done}',
    attacking: 'attacking the {name}',
    hpLine: 'HP {hp}/{max}',
    // The crew chooser and the heroes list.
    crewNewTitle: 'New {name}',
    crewOfTitle: '{name} crew',
    crewHintNew: 'Up to {n}; the best at home for the work are ticked.',
    crewHintBand: 'Up to {n}; the best fighters at home are ticked.',
    crewHint: 'Up to {n}. Those you untick go home; those you tick come here.',
    order: 'Order',
    sortDefault: 'Default',
    sortDefaultTitle: 'Those ticked first, then those at home, the best at the work first',
    sortHero: 'Hero',
    sortHeroTitle: 'Heroes first, who level up faster; then the highest level',
    sortLevel: 'Level',
    sortLevelTitle: 'Highest level first',
    sortNear: 'Nearest',
    sortNearTitle: 'Closest to the building first',
    sortSkillTitle: 'Best at {skill} first',
    sortAttack: 'Attack',
    crewCount: '{n} of {max}',
    cancel: 'Cancel',
    send: 'Send',
    okTitle: '{action} (Enter or {key})',
    heroTitle: 'A hero: levels up faster than the rest',
    skillRanged: 'Ranged attack',
    skillMelee: 'Close combat',
    skillBuild: 'Building',
    skillFarming: 'Farming',
    skillBreeding: 'Breeding',
    skillRunning: 'Running',
    whereOutside: 'outside',
    whereHere: 'here',
    whereComing: 'on the way here',
    whereHome: 'at home',
    whereGoingHome: 'going home',
    whereIn: 'in a {name}',
    whereTo: 'going to a {name}',
    diedHunger: 'died of hunger',
    diedCombat: 'died in combat',
    heroesHeading: 'Heroes',
    heroesHint: 'Highest level first, then the fallen. {skills}',
    heroesCount: { one: '{n} hero of {total} units', other: '{n} heroes of {total} units' },
    fallenCount: { one: '{n} fallen', other: '{n} fallen' },
    heroesNoneAlive: 'None alive.',
    heroesNoneYet: 'None yet: about one unit in ten is born a hero.',
    close: 'Close',
    // The table of points at a game's end.
    scoresGameOver: 'Game over',
    scoresYouWon: 'You won',
    scoresYouLost: 'You lost',
    scoresNobody: '{time} · nobody won',
    scoresWon: '{time} · {sides} won',
    quickWinNote: 'quick win: points ×{times}',
    scoresSide: 'Side',
    scoresTotal: 'Total',
    scoresBonus: 'Bonus',
    scoresBonusTitle: 'Quick win: the winners\' points are multiplied, {ranges}',
    quickWinRange: '×{times} for {from}–{to} minutes',
    scoreWon: 'Win',
    scoreWonWhat: 'for the winning team',
    scoreCastles: 'Castles',
    scoreCastlesWhat: 'enemy castles and lairs brought down',
    scoreFelled: 'Felled',
    scoreFelledWhat: 'enemy buildings brought down',
    scoreKills: 'Kills',
    scoreKillsWhat: 'enemy units killed',
    scoreDamage: 'Damage',
    scoreDamageWhat: 'hit points taken off enemy buildings',
    scoreUpgrades: 'Upgrades',
    scoreUpgradesWhat: 'grades reached by upgrading',
    scoreBuilt: 'Built',
    scoreBuiltWhat: 'buildings finished',
    scoreBorn: 'Born',
    scoreBornWhat: 'units born',
    scoreStone: 'Stone',
    scoreStoneWhat: 'stone dug',
    scoreFood: 'Food',
    scoreFoodWhat: 'food grown by crews',
    pointsEach: { one: '{n} point each', other: '{n} points each' },
    pointPer: 'a point per {n}',
    keepWatching: 'Keep watching',
    leaveMatch: 'Leave the match',
    // The keys that press the buttons, each a letter of its label, shown in
    // bold. The English ones work in every language.
    keyTower: 'T',
    keyWagon: 'W',
    keyPit: 'P',
    keyFarm: 'F',
    keyBand: 'B',
    keyUpgrade: 'U',
    keyCrew: 'C',
    keyHeroes: 'H',
    keyAttack: 'A',
  },
  ru: {
    name: 'Ваше имя',
    namePlaceholder: 'Имя в игре ({max})',
    language: 'Язык',
    auto: 'Авто',
    badName: 'От 1 до {max} букв или цифр. Между ними можно пробел и - _ . \'',
    refused: 'Сервер отказал ({why}).',
    offline: 'Нет связи с игровым сервером.',
    play: 'Играть',
    loading: 'Загружаем вопрос…',
    question: 'Сколько будет {sum}?',
    noQuestion: 'Вопрос не загрузился. Нажмите «Играть» ещё раз.',
    wrongAnswer: 'Неверно. Вот другой пример.',
    settings: 'Настройки',
    back: 'Назад',
    save: 'Сохранить',
    playingAs: 'Игрок:',
    mode: 'Режим',
    players: 'Игроки',
    newGame: 'Новая игра',
    coopChoice: 'Кооператив: вместе против Тёмного Лорда',
    easyChoice: 'Лёгкий Лорд: вместе против слабого Тёмного Лорда',
    veryEasyChoice: 'Очень Лёгкий Лорд: как Общий Лёгкий, и юниты плодятся вдвое быстрее',
    sharedChoice: 'Общий Лёгкий Лорд: один запас на всех, против слабого Тёмного Лорда',
    ffaChoice: 'Все против всех: каждый сам за себя',
    yourGames: 'Ваши игры',
    yourGamesNone: 'Пока нет. Начните игру или войдите в одну ниже.',
    waitingGames: 'Ждут игрока',
    waitingGamesNone: 'Сейчас никто не ждёт.',
    ongoingGames: 'Идут сейчас',
    ongoingGamesNone: 'Больше никто сейчас не играет.',
    finishedGames: 'Недавно закончились',
    finishedGamesNone: 'Ни одна игра ещё не закончилась.',
    howToPlay: 'Как играть',
    about: 'Об игре',
    open: 'Открыть',
    join: 'Войти',
    watch: 'Смотреть',
    scores: 'Итоги',
    delete: 'Удалить',
    leave: 'Выйти',
    deleteTitle: 'Удалить навсегда: больше никто в неё не играет',
    leaveTitle: 'Освободить своё место для другого игрока',
    askDelete: 'Удалить «{game}» навсегда?',
    askLeave: 'Выйти из «{game}»? Ваше место займёт следующий.',
    deleted: 'Игра «{game}» удалена.',
    left: 'Вы вышли из «{game}».',
    notDeleted: 'Не удалось удалить «{game}» ({why}).',
    notLeft: 'Не удалось выйти из «{game}» ({why}).',
    notStarted: 'Не удалось начать игру ({why}).',
    noSuchGame: 'По этому адресу игры нет.',
    notOpened: 'Не удалось открыть эту игру.',
    aGame: 'Игра',
    tooMany: 'Слишком много игр: {reasons}. Вернитесь в одну из них или уберите одну, чтобы начать новую:',
    tooManyWaiting: {
      one: '{n} ваша ждёт игрока',
      few: '{n} ваши ждут игрока',
      many: '{n} ваших ждут игрока',
      other: '{n} ваших ждут игрока',
    },
    tooManySeated: {
      one: 'вы играете в {n} идущей игре',
      few: 'вы играете в {n} идущих играх',
      many: 'вы играете в {n} идущих играх',
      other: 'вы играете в {n} идущих играх',
    },
    and: ' и ',
    coop: 'Кооператив',
    easy: 'Лёгкий Лорд',
    veryEasy: 'Очень Лёгкий Лорд',
    shared: 'Общий Лёгкий Лорд',
    ffa: 'Все против всех',
    nobodyWon: 'конец, без победителя',
    won: 'победа',
    lordWon: 'победил Тёмный Лорд',
    sideWon: 'победили {side}',
    blue: 'Синие',
    crimson: 'Багровые',
    green: 'Зелёные',
    gold: 'Золотые',
    teal: 'Бирюзовые',
    orange: 'Оранжевые',
    rose: 'Розовые',
    silver: 'Серебряные',
    azure: 'Лазурные',
    lime: 'Салатовые',
    indigo: 'Индиго',
    cherry: 'Вишнёвые',
    olive: 'Оливковые',
    coral: 'Коралловые',
    white: 'Белые',
    mint: 'Мятные',
    groupBuild: 'Строить',
    groupSelected: 'Выбрано',
    groupView: 'Вид',
    tower: 'Башня',
    // Воз and Яма, not Повозка and Карьер: with either, Upgrade no longer
    // fits in the phone's first row of buttons, and the second row wraps.
    wagon: 'Воз',
    pit: 'Яма',
    farm: 'Ферма',
    band: 'Отряд',
    // Апгрейд, not Улучшить: it keeps Upgrade in the phone's first row.
    upgrade: 'Апгрейд',
    crew: 'Бригада…',
    heroes: 'Герои…',
    return: 'Вернуть',
    abort: 'Бросить',
    attack: 'Атака…',
    recenter: 'Центр',
    mute: 'Тихо',
    coordinates: 'Координаты',
    releaseSeat: 'Отпусти',
    takeSeat: 'Занять место',
    newBase: 'Новая база',
    newBaseTitle: 'Ваш замок пал: играйте дальше за свободный, за выбранный, если он свободен',
    startNow: 'Старт',
    goOn: 'Дальше',
    startNowTitle: 'Начать без отсутствующих: Тёмный Лорд не идёт на их замки, пока они не вернутся',
    lobby: 'Лобби',
    zoomOut: 'Отдалить',
    zoomIn: 'Приблизить',
    buildTitle: '{name} ({key}): {price}',
    stoneCost: { one: '{n} камень', few: '{n} камня', many: '{n} камней', other: '{n} камня' },
    metalCost: '{n} тёмного металла, возле вашего замка',
    hungerCost: '+{n}% к голоду (бесплатно при 100%)',
    free: 'бесплатно',
    upgradeTitle: 'Апгрейд (Г)',
    crewTitle: 'Выбрать, кто здесь работает (Д)',
    heroesTitle: 'Ваши герои, сильнейшие первыми (Р)',
    abortTitle: 'Бросить недостроенное здание: бригада идёт домой, затраты пропадают',
    attackTitle: 'Атака (Т)',
    muteTitle: 'Звук включён, пока кнопка не нажата; выбор помнит этот браузер',
    statusFold: 'Скрыть сведения об игре',
    statusUnfold: 'Показать сведения об игре',
    minimapHide: 'Скрыть миникарту (M)',
    minimapShow: 'Показать миникарту (M)',
    masthead: 'Vigame · прототип',
    statusGame: 'Игра',
    statusTime: 'Время',
    statusYou: 'Вы',
    statusUnits: 'Юниты',
    statusTile: 'Клетка',
    statusObservers: 'Зрители',
    renameTitle: 'Переименовать игру',
    playersTitle: 'Игроки на местах, кто здесь, из всех мест; мигает, пока игра ждёт остальных',
    paused: 'пауза',
    pausedTitle: 'Игра ждёт, пока соберутся все игроки',
    overYouWon: 'конец: вы победили',
    overYouLost: 'конец: вы проиграли',
    overSideWon: 'конец: победили {side}',
    spectator: 'Зритель',
    awayCount: 'отошли: {n}',
    offlineShort: 'нет связи',
    grass: 'Трава',
    meadow: 'Луг',
    scrub: 'Кустарник',
    water: 'Вода',
    impassable: 'не пройти',
    noBuilding: 'строить нельзя',
    darkLord: 'Тёмный Лорд',
    raiders: 'Разбойники',
    stone: 'Камень',
    darkMetal: 'Тёмный металл',
    food: 'Еда',
    teamStone: 'Общ. камень',
    teamDarkMetal: 'Общ. металл',
    teamFood: 'Общ. еда',
    hungerShort: 'голод {n}%',
    stoneTitle: 'Жирным от 60: хватит на башню',
    metalTitle: 'Жирным от 30: хватит на апгрейд воза',
    foodCountTitle: 'Жирным, когда запаса с тем, что дадут замок и фермы, не хватит всем юнитам на полный обед',
    foodStoreTitle: 'Больше запас не вмещает',
    nothingSelected: 'Ничего не выбрано',
    minimapLabel: 'Карта всего поля: нажмите или проведите по ней, чтобы смотреть туда',
    castle: 'Замок',
    lair: 'Логово',
    ghoul: 'Упырь',
    ogre: 'Огр',
    raider: 'Разбойник',
    graded: '{name} (ур. {n})',
    atHome: '{n}/{max} дома',
    nextUnit: 'новый юнит {done}',
    crewLine: 'бригада {n}/{max}',
    levelLine: 'уровень {n}',
    upgrading: 'апгрейд {done}',
    goingUp: 'стройка {done}',
    dugOut: 'выкопана',
    depthLine: 'глубина {n}/{max}, {stone}',
    nextFood: 'еда {done}',
    attacking: 'цель: {name}',
    hpLine: 'Прочность {hp}/{max}',
    crewNewTitle: 'Стройка: {name}',
    crewOfTitle: 'Бригада: {name}',
    crewHintNew: 'До {n}; отмечены лучшие для этой работы из тех, кто дома.',
    crewHintBand: 'До {n}; отмечены лучшие бойцы из тех, кто дома.',
    crewHint: 'До {n}. Без отметки — домой, с отметкой — сюда.',
    order: 'Порядок',
    sortDefault: 'Обычный',
    sortDefaultTitle: 'Сначала отмеченные, потом те, кто дома, лучшие в работе первыми',
    sortHero: 'Герой',
    sortHeroTitle: 'Сначала герои, они растут быстрее; потом по уровню',
    sortLevel: 'Уровень',
    sortLevelTitle: 'Сначала высший уровень',
    sortNear: 'Ближние',
    sortNearTitle: 'Сначала ближайшие к зданию',
    sortSkillTitle: 'Сначала лучшие: {skill}',
    sortAttack: 'Атака',
    crewCount: '{n} из {max}',
    cancel: 'Отмена',
    send: 'Отправить',
    okTitle: '{action} (Enter или {key})',
    heroTitle: 'Герой: растёт быстрее остальных',
    skillRanged: 'Стрельба',
    skillMelee: 'Ближний бой',
    skillBuild: 'Стройка',
    skillFarming: 'Земледелие',
    skillBreeding: 'Плодовитость',
    skillRunning: 'Бег',
    whereOutside: 'снаружи',
    whereHere: 'здесь',
    whereComing: 'идёт сюда',
    whereHome: 'дома',
    whereGoingHome: 'идёт домой',
    whereIn: '{name}',
    whereTo: '→ {name}',
    diedHunger: 'умер от голода',
    diedCombat: 'пал в бою',
    heroesHeading: 'Герои',
    heroesHint: 'Сначала высший уровень, потом павшие. {skills}',
    heroesCount: { one: '{n} герой из {total}', few: '{n} героя из {total}', many: '{n} героев из {total}', other: '{n} героя из {total}' },
    fallenCount: { one: '{n} павший', few: '{n} павших', many: '{n} павших', other: '{n} павших' },
    heroesNoneAlive: 'Живых нет.',
    heroesNoneYet: 'Пока нет: героем рождается примерно каждый десятый.',
    close: 'Закрыть',
    scoresGameOver: 'Игра окончена',
    scoresYouWon: 'Вы победили',
    scoresYouLost: 'Вы проиграли',
    scoresNobody: '{time} · без победителя',
    scoresWon: '{time} · победили {sides}',
    quickWinNote: 'быстрая победа: очки ×{times}',
    scoresSide: 'Сторона',
    scoresTotal: 'Всего',
    scoresBonus: 'Бонус',
    scoresBonusTitle: 'Быстрая победа: очки победителей умножаются, {ranges}',
    quickWinRange: '×{times} за {from}–{to} минут',
    scoreWon: 'Победа',
    scoreWonWhat: 'команде-победителю',
    scoreCastles: 'Замки',
    scoreCastlesWhat: 'вражеских замков и логов снесено',
    scoreFelled: 'Снесено',
    scoreFelledWhat: 'вражеских зданий снесено',
    scoreKills: 'Убито',
    scoreKillsWhat: 'вражеских юнитов убито',
    scoreDamage: 'Урон',
    scoreDamageWhat: 'прочности снято с вражеских зданий',
    scoreUpgrades: 'Апгрейды',
    scoreUpgradesWhat: 'уровней получено апгрейдами',
    scoreBuilt: 'Построено',
    scoreBuiltWhat: 'зданий достроено',
    scoreBorn: 'Рождено',
    scoreBornWhat: 'юнитов родилось',
    scoreStone: 'Камень',
    scoreStoneWhat: 'камня добыто',
    scoreFood: 'Еда',
    scoreFoodWhat: 'еды выращено бригадами',
    pointsEach: { one: '{n} очко за каждое', few: '{n} очка за каждое', many: '{n} очков за каждое', other: '{n} очка за каждое' },
    pointPer: 'очко за каждые {n}',
    keepWatching: 'Смотреть дальше',
    leaveMatch: 'Покинуть матч',
    // On the same key as the English one where the word has its letter (Г
    // is on U, Р on H, А on F), else the first letter, else a letter on a key
    // English leaves free (Б and А were taken): never on another button's
    // English key, as those work here too.
    keyTower: 'Б',
    keyWagon: 'В',
    keyPit: 'Я',
    keyFarm: 'А',
    keyBand: 'О',
    keyUpgrade: 'Г',
    keyCrew: 'Д',
    keyHeroes: 'Р',
    keyAttack: 'Т',
  },
  lv: {
    name: 'Jūsu vārds',
    namePlaceholder: 'Redzamais vārds ({max})',
    language: 'Valoda',
    auto: 'Auto',
    badName: 'Lietojiet 1–{max} burtus vai ciparus; starp tiem drīkst būt atstarpe un - _ . \'',
    refused: 'Serveris atteica ({why}).',
    offline: 'Nevar sazināties ar spēles serveri.',
    play: 'Spēlēt',
    loading: 'Ielādē jautājumu…',
    question: 'Cik ir {sum}?',
    noQuestion: 'Jautājums neielādējās. Nospiediet „Spēlēt”, lai mēģinātu vēlreiz.',
    wrongAnswer: 'Nepareizi. Mēģiniet šo.',
    settings: 'Iestatījumi',
    back: 'Atpakaļ',
    save: 'Saglabāt',
    playingAs: 'Spēlētājs:',
    mode: 'Režīms',
    players: 'Spēlētāji',
    newGame: 'Jauna spēle',
    coopChoice: 'Sadarbība: kopā pret Tumšo Kungu',
    easyChoice: 'Vieglais Kungs: kopā pret vājāku Tumšo Kungu',
    veryEasyChoice: 'Ļoti Vieglais Kungs: kā Kopīgais Vieglais, un vienības vairojas divreiz ātrāk',
    sharedChoice: 'Kopīgais Vieglais Kungs: viens krājums visiem, pret vājāku Tumšo Kungu',
    ffaChoice: 'Visi pret visiem: katrs par sevi',
    yourGames: 'Jūsu spēles',
    yourGamesNone: 'Vēl nav. Sāciet kādu vai pievienojieties zemāk.',
    waitingGames: 'Gaida spēlētāju',
    waitingGamesNone: 'Pašlaik neviens negaida.',
    ongoingGames: 'Notiek',
    ongoingGamesNone: 'Pašlaik neviens cits nespēlē.',
    finishedGames: 'Nesen beigušās',
    finishedGamesNone: 'Neviena spēle vēl nav beigusies.',
    howToPlay: 'Kā spēlēt',
    about: 'Par spēli',
    open: 'Atvērt',
    join: 'Ienākt',
    watch: 'Skatīties',
    scores: 'Rezultāti',
    delete: 'Dzēst',
    leave: 'Pamest',
    deleteTitle: 'Dzēst pavisam: neviens cits to nespēlē',
    leaveTitle: 'Atdot savu vietu kādam citam',
    askDelete: 'Dzēst „{game}” pavisam?',
    askLeave: 'Pamest „{game}”? Jūsu vietu aizņems nākamais.',
    deleted: '„{game}” izdzēsta.',
    left: 'Jūs pametāt „{game}”.',
    notDeleted: 'Neizdevās izdzēst „{game}” ({why}).',
    notLeft: 'Neizdevās pamest „{game}” ({why}).',
    notStarted: 'Neizdevās sākt spēli ({why}).',
    noSuchGame: 'Šajā adresē spēles nav.',
    notOpened: 'Neizdevās atvērt šo spēli.',
    aGame: 'Spēle',
    tooMany: 'Par daudz spēļu: {reasons}. Atgriezieties kādā no tām vai atbrīvojiet vienu, lai sāktu jaunu:',
    tooManyWaiting: {
      zero: '{n} jūsu spēles gaida spēlētāju',
      one: '{n} jūsu spēle gaida spēlētāju',
      other: '{n} jūsu spēles gaida spēlētāju',
    },
    tooManySeated: {
      zero: 'jūs spēlējat {n} notiekošās spēlēs',
      one: 'jūs spēlējat {n} notiekošā spēlē',
      other: 'jūs spēlējat {n} notiekošās spēlēs',
    },
    and: ' un ',
    coop: 'Sadarbība',
    easy: 'Vieglais Kungs',
    veryEasy: 'Ļoti Vieglais Kungs',
    shared: 'Kopīgais Vieglais Kungs',
    ffa: 'Visi pret visiem',
    nobodyWon: 'beigas, bez uzvarētāja',
    won: 'uzvara',
    lordWon: 'uzvarēja Tumšais Kungs',
    sideWon: 'uzvarēja {side}',
    blue: 'Zilie',
    crimson: 'Sarkanie',
    green: 'Zaļie',
    gold: 'Zelta',
    teal: 'Tirkīza',
    orange: 'Oranžie',
    rose: 'Rozā',
    silver: 'Sudraba',
    azure: 'Debeszilie',
    lime: 'Laima',
    indigo: 'Indigo',
    cherry: 'Ķiršu',
    olive: 'Olīvu',
    coral: 'Koraļļu',
    white: 'Baltie',
    mint: 'Mētru',
    groupBuild: 'Būvēt',
    groupSelected: 'Izvēlēts',
    groupView: 'Skats',
    tower: 'Tornis',
    wagon: 'Rati',
    pit: 'Bedre',
    farm: 'Ferma',
    band: 'Bars',
    upgrade: 'Uzlabot',
    crew: 'Komanda…',
    heroes: 'Varoņi…',
    return: 'Mājās',
    abort: 'Atcelt',
    // Atakot, not Uzbrukt: it keeps A, the English key.
    attack: 'Atakot…',
    recenter: 'Centrēt',
    mute: 'Kluss',
    coordinates: 'Koordinātas',
    releaseSeat: 'Atlaist',
    takeSeat: 'Sēsties',
    newBase: 'Jauna bāze',
    newBaseTitle: 'Jūsu pils krita: spēlējiet tālāk ar brīvu, ar izvēlēto, ja tā ir brīva',
    startNow: 'Sākt',
    goOn: 'Turpināt',
    startNowTitle: 'Sākt bez trūkstošajiem: Tumšais Kungs neiet uz viņu pilīm, kamēr viņi nav atpakaļ',
    lobby: 'Lobijs',
    zoomOut: 'Attālināt',
    zoomIn: 'Pietuvināt',
    buildTitle: '{name} ({key}): {price}',
    stoneCost: { zero: '{n} akmens', one: '{n} akmens', other: '{n} akmens' },
    metalCost: '{n} tumšā metāla, pie jūsu pils',
    hungerCost: '+{n}% bada (bezmaksas pie 100%)',
    free: 'bezmaksas',
    upgradeTitle: 'Uzlabot (U)',
    crewTitle: 'Izvēlēties, kas šeit strādā (K)',
    heroesTitle: 'Jūsu varoņi, augstākais līmenis pirmais (V)',
    abortTitle: 'Atteikties no ēkas, kas vēl top: komanda iet mājās, izmaksas zūd',
    attackTitle: 'Atakot (A)',
    muteTitle: 'Skaņa ir ieslēgta, ja vien šī nav nospiesta; izvēli atceras šis pārlūks',
    statusFold: 'Paslēpt spēles ziņas',
    statusUnfold: 'Rādīt spēles ziņas',
    minimapHide: 'Paslēpt minikarti (M)',
    minimapShow: 'Rādīt minikarti (M)',
    masthead: 'Vigame · prototips',
    statusGame: 'Spēle',
    statusTime: 'Laiks',
    statusYou: 'Jūs',
    statusUnits: 'Vienības',
    statusTile: 'Lauciņš',
    statusObservers: 'Skatītāji',
    renameTitle: 'Pārdēvēt spēli',
    playersTitle: 'Klātesošie spēlētāji no visām vietām; mirgo, kamēr spēle gaida pārējos',
    paused: 'pauze',
    pausedTitle: 'Spēle gaida, kamēr visi spēlētāji būs klāt',
    overYouWon: 'beigas: uzvara',
    overYouLost: 'beigas: zaudējums',
    overSideWon: 'beigas: uzvarēja {side}',
    spectator: 'Skatītājs',
    awayCount: 'prom: {n}',
    offlineShort: 'bezsaistē',
    grass: 'Zāle',
    meadow: 'Pļava',
    scrub: 'Krūmi',
    water: 'Ūdens',
    impassable: 'neizbrienams',
    noBuilding: 'būvēt nevar',
    darkLord: 'Tumšais Kungs',
    raiders: 'Laupītāji',
    stone: 'Akmens',
    darkMetal: 'Tumšais metāls',
    food: 'Pārtika',
    teamStone: 'Kop. akmens',
    teamDarkMetal: 'Kop. metāls',
    teamFood: 'Kop. pārtika',
    hungerShort: 'bads {n}%',
    stoneTitle: 'Treknrakstā no 60: pietiek tornim',
    metalTitle: 'Treknrakstā no 30: pietiek vāģa uzlabojumam',
    foodCountTitle: 'Treknrakstā, kad krājums ar to, ko līdz tam dos pils un fermas, nepabaros visas vienības līdz galam',
    foodStoreTitle: 'Vairāk krājumā nesaiet',
    nothingSelected: 'Nekas nav izvēlēts',
    minimapLabel: 'Visa laukuma karte: nospiediet vai velciet pa to, lai skatītos tur',
    castle: 'Pils',
    lair: 'Midzenis',
    ghoul: 'Gūls',
    ogre: 'Ogrs',
    raider: 'Laupītājs',
    graded: '{name} ({n}. līmenis)',
    atHome: '{n}/{max} mājās',
    nextUnit: 'nākamā vienība {done}',
    crewLine: 'komanda {n}/{max}',
    levelLine: 'līmenis {n}',
    upgrading: 'uzlabo {done}',
    goingUp: 'ceļ {done}',
    dugOut: 'izrakta',
    depthLine: 'dziļums {n}/{max}, {stone}',
    nextFood: 'pārtika {done}',
    attacking: 'mērķis: {name}',
    hpLine: 'Izturība {hp}/{max}',
    crewNewTitle: 'Būve: {name}',
    crewOfTitle: 'Komanda: {name}',
    crewHintNew: 'Līdz {n}; atzīmēti labākie šim darbam no tiem, kas mājās.',
    crewHintBand: 'Līdz {n}; atzīmēti labākie cīnītāji no tiem, kas mājās.',
    crewHint: 'Līdz {n}. Bez atzīmes — uz mājām, ar atzīmi — šurp.',
    order: 'Secība',
    sortDefault: 'Parasti',
    sortDefaultTitle: 'Vispirms atzīmētie, tad mājās esošie, labākie darbā pirmie',
    sortHero: 'Varonis',
    sortHeroTitle: 'Vispirms varoņi, kas aug ātrāk; tad pēc līmeņa',
    sortLevel: 'Līmenis',
    sortLevelTitle: 'Vispirms augstākais līmenis',
    sortNear: 'Tuvākie',
    sortNearTitle: 'Vispirms ēkai tuvākie',
    sortSkillTitle: 'Vispirms labākie: {skill}',
    sortAttack: 'Uzbrukums',
    crewCount: '{n} no {max}',
    cancel: 'Atcelt',
    send: 'Sūtīt',
    okTitle: '{action} (Enter vai {key})',
    heroTitle: 'Varonis: aug ātrāk par citiem',
    skillRanged: 'Šaušana',
    skillMelee: 'Tuvcīņa',
    skillBuild: 'Būvēšana',
    skillFarming: 'Zemkopība',
    skillBreeding: 'Vairošanās',
    skillRunning: 'Skriešana',
    whereOutside: 'ārā',
    whereHere: 'šeit',
    whereComing: 'nāk šurp',
    whereHome: 'mājās',
    whereGoingHome: 'iet mājās',
    whereIn: '{name}',
    whereTo: '→ {name}',
    diedHunger: 'nomira badā',
    diedCombat: 'krita kaujā',
    heroesHeading: 'Varoņi',
    heroesHint: 'Vispirms augstākais līmenis, tad kritušie. {skills}',
    heroesCount: { zero: '{n} varoņu no {total}', one: '{n} varonis no {total}', other: '{n} varoņi no {total}' },
    fallenCount: { zero: '{n} kritušo', one: '{n} kritušais', other: '{n} kritušie' },
    heroesNoneAlive: 'Dzīvu nav.',
    heroesNoneYet: 'Vēl nav: varonis piedzimst apmēram katrs desmitais.',
    close: 'Aizvērt',
    scoresGameOver: 'Spēles beigas',
    scoresYouWon: 'Uzvara!',
    scoresYouLost: 'Zaudējums',
    scoresNobody: '{time} · bez uzvarētāja',
    scoresWon: '{time} · uzvarēja {sides}',
    quickWinNote: 'ātra uzvara: punkti ×{times}',
    scoresSide: 'Puse',
    scoresTotal: 'Kopā',
    scoresBonus: 'Bonuss',
    scoresBonusTitle: 'Ātra uzvara: uzvarētāju punkti tiek reizināti, {ranges}',
    quickWinRange: '×{times} par {from}–{to} minūtēm',
    scoreWon: 'Uzvara',
    scoreWonWhat: 'uzvarētāju komandai',
    scoreCastles: 'Pilis',
    scoreCastlesWhat: 'nojauktas ienaidnieka pilis un midzeņi',
    scoreFelled: 'Nojauktas',
    scoreFelledWhat: 'nojauktas ienaidnieka ēkas',
    scoreKills: 'Nogalināti',
    scoreKillsWhat: 'nogalināti ienaidnieki',
    scoreDamage: 'Bojājumi',
    scoreDamageWhat: 'ienaidnieka ēkām atņemtā izturība',
    scoreUpgrades: 'Uzlabojumi',
    scoreUpgradesWhat: 'uzlabojot sasniegtie līmeņi',
    scoreBuilt: 'Uzbūvēts',
    scoreBuiltWhat: 'pabeigtas ēkas',
    scoreBorn: 'Dzimuši',
    scoreBornWhat: 'dzimušie',
    scoreStone: 'Akmens',
    scoreStoneWhat: 'izrakts akmens',
    scoreFood: 'Pārtika',
    scoreFoodWhat: 'komandu izaudzēta pārtika',
    pointsEach: { zero: '{n} punktu par katru', one: '{n} punkts par katru', other: '{n} punkti par katru' },
    pointPer: 'punkts par katriem {n}',
    keepWatching: 'Skatīties tālāk',
    leaveMatch: 'Pamest spēli',
    // As in Russian: the English key where the word has it (T, F, B, U, A),
    // else the first letter, else a free one (B**e**dre: B is Band's).
    // Latvian keyboards have the English letters on the same keys.
    keyTower: 'T',
    keyWagon: 'R',
    keyPit: 'E',
    keyFarm: 'F',
    keyBand: 'B',
    keyUpgrade: 'U',
    keyCrew: 'K',
    keyHeroes: 'V',
    keyAttack: 'A',
  },
  fi: {
    name: 'Nimesi',
    namePlaceholder: 'Näkyvä nimi ({max})',
    language: 'Kieli',
    auto: 'Auto',
    badName: 'Käytä 1–{max} kirjainta tai numeroa. Välilyönti ja - _ . \' käyvät niiden välissä.',
    refused: 'Palvelin kieltäytyi ({why}).',
    offline: 'Pelipalvelimeen ei saatu yhteyttä.',
    play: 'Pelaa',
    loading: 'Ladataan kysymystä…',
    question: 'Paljonko on {sum}?',
    noQuestion: 'Kysymystä ei voitu ladata. Yritä uudelleen painamalla Pelaa.',
    wrongAnswer: 'Väärin. Kokeile tätä.',
    settings: 'Asetukset',
    back: 'Takaisin',
    save: 'Tallenna',
    playingAs: 'Pelaaja:',
    mode: 'Pelitila',
    players: 'Pelaajat',
    newGame: 'Uusi peli',
    coopChoice: 'Yhteistyö: yhdessä Pimeää Herraa vastaan',
    easyChoice: 'Helppo Herra: yhdessä heikompaa Pimeää Herraa vastaan',
    veryEasyChoice: 'Hyvin Helppo Herra: kuin Yhteinen Helppo, ja yksiköt lisääntyvät kaksi kertaa nopeammin',
    sharedChoice: 'Yhteinen Helppo Herra: yhteiset varastot, heikompaa Pimeää Herraa vastaan',
    ffaChoice: 'Vapaa ottelu: jokainen kaikkia vastaan',
    yourGames: 'Omat pelisi',
    yourGamesNone: 'Ei vielä. Aloita peli tai liity alla olevaan.',
    waitingGames: 'Odottaa pelaajaa',
    waitingGamesNone: 'Kukaan ei odota juuri nyt.',
    ongoingGames: 'Käynnissä',
    ongoingGamesNone: 'Kukaan muu ei pelaa juuri nyt.',
    finishedGames: 'Äskettäin päättyneet',
    finishedGamesNone: 'Ei vielä päättyneitä pelejä.',
    howToPlay: 'Näin pelaat',
    about: 'Tietoja',
    open: 'Avaa',
    join: 'Liity',
    watch: 'Katso',
    scores: 'Pisteet',
    delete: 'Poista',
    leave: 'Poistu',
    deleteTitle: 'Poista lopullisesti: kukaan muu ei pelaa sitä',
    leaveTitle: 'Luovu paikastasi jollekulle toiselle',
    askDelete: 'Poistetaanko ”{game}” lopullisesti?',
    askLeave: 'Poistutaanko pelistä ”{game}”? Paikkasi saa seuraava tulija.',
    deleted: '”{game}” poistettu.',
    left: '”{game}” jätetty.',
    notDeleted: 'Ei voitu poistaa: ”{game}” ({why}).',
    notLeft: 'Ei voitu poistua: ”{game}” ({why}).',
    notStarted: 'Pelin aloittaminen ei onnistunut ({why}).',
    noSuchGame: 'Tässä osoitteessa ei ole peliä.',
    notOpened: 'Peliä ei voitu avata.',
    aGame: 'Peli',
    tooMany: 'Liian monta peliä: {reasons}. Palaa johonkin niistä tai vapauta yksi ennen uuden aloittamista:',
    tooManyWaiting: { one: '{n} pelisi odottaa pelaajaa', other: '{n} peliäsi odottaa pelaajaa' },
    tooManySeated: { one: 'paikka {n} käynnissä olevassa pelissä', other: 'paikka {n} käynnissä olevassa pelissä' },
    and: ' ja ',
    coop: 'Yhteistyö',
    easy: 'Helppo Herra',
    veryEasy: 'Hyvin Helppo Herra',
    shared: 'Yhteinen Helppo Herra',
    ffa: 'Vapaa ottelu',
    nobodyWon: 'päättyi, ei voittajaa',
    won: 'voitto',
    lordWon: 'Pimeä Herra voitti',
    sideWon: 'voitto: {side}',
    blue: 'Siniset',
    crimson: 'Punaiset',
    green: 'Vihreät',
    gold: 'Kultaiset',
    teal: 'Turkoosit',
    orange: 'Oranssit',
    rose: 'Roosat',
    silver: 'Hopeiset',
    azure: 'Asuurit',
    lime: 'Limetit',
    indigo: 'Indigot',
    cherry: 'Kirsikat',
    olive: 'Oliivit',
    coral: 'Korallit',
    white: 'Valkoiset',
    mint: 'Mintut',
    groupBuild: 'Rakenna',
    groupSelected: 'Valittu',
    groupView: 'Näkymä',
    tower: 'Torni',
    wagon: 'Vaunu',
    pit: 'Kuoppa',
    // Farmi, not Tila: it keeps F, the English key.
    farm: 'Farmi',
    band: 'Joukko',
    upgrade: 'Kehitä',
    crew: 'Ryhmä…',
    heroes: 'Sankarit…',
    return: 'Kotiin',
    abort: 'Peru',
    attack: 'Hyökkää…',
    recenter: 'Keskitä',
    mute: 'Hiljaa',
    coordinates: 'Koordinaatit',
    releaseSeat: 'Vapauta',
    takeSeat: 'Istu',
    newBase: 'Uusi linna',
    newBaseTitle: 'Linnasi kaatui: jatka vapaalla linnalla, valitulla, jos se on vapaa',
    startNow: 'Aloita',
    goOn: 'Jatka',
    startNowTitle: 'Aloita ilman puuttuvia: Pimeä Herra jättää heidän linnansa rauhaan, kunnes he palaavat',
    lobby: 'Aula',
    zoomOut: 'Loitonna',
    zoomIn: 'Lähennä',
    buildTitle: '{name} ({key}): {price}',
    stoneCost: { one: '{n} kivi', other: '{n} kiveä' },
    metalCost: '{n} tummaa metallia, linnasi lähellä',
    hungerCost: '{n}% lisää nälkää (ilmainen, kun nälkä on 100%)',
    free: 'ilmainen',
    upgradeTitle: 'Kehitä (K)',
    crewTitle: 'Valitse, kuka täällä työskentelee (R)',
    heroesTitle: 'Sankarisi, korkein taso ensin (S)',
    abortTitle: 'Luovu keskeneräisestä rakennuksesta: ryhmä palaa kotiin, kulut menetetään',
    attackTitle: 'Hyökkää (Y)',
    muteTitle: 'Äänet ovat päällä, ellei tätä ole painettu; tämä selain muistaa valinnan',
    statusFold: 'Piilota pelin tiedot',
    statusUnfold: 'Näytä pelin tiedot',
    minimapHide: 'Piilota pikkukartta (M)',
    minimapShow: 'Näytä pikkukartta (M)',
    masthead: 'Vigame · prototyyppi',
    statusGame: 'Peli',
    statusTime: 'Aika',
    statusYou: 'Sinä',
    statusUnits: 'Yksiköt',
    statusTile: 'Ruutu',
    statusObservers: 'Katsojat',
    renameTitle: 'Nimeä peli uudelleen',
    playersTitle: 'Paikalla olevat pelaajat kaikista paikoista; vilkkuu, kun peli odottaa muita',
    paused: 'tauko',
    pausedTitle: 'Peli odottaa, kunnes kaikki pelaajat ovat paikalla',
    overYouWon: 'ohi: voitit',
    overYouLost: 'ohi: hävisit',
    overSideWon: 'ohi, voittaja: {side}',
    spectator: 'Katsoja',
    awayCount: 'poissa: {n}',
    offlineShort: 'ei yhteyttä',
    grass: 'Ruoho',
    meadow: 'Niitty',
    scrub: 'Pensaikko',
    water: 'Vesi',
    impassable: 'ei kulkua',
    noBuilding: 'ei rakentamista',
    darkLord: 'Pimeä Herra',
    raiders: 'Rosvot',
    stone: 'Kivi',
    darkMetal: 'Tumma metalli',
    food: 'Ruoka',
    teamStone: 'Yht. kivi',
    teamDarkMetal: 'Yht. metalli',
    teamFood: 'Yht. ruoka',
    hungerShort: 'nälkä {n}%',
    stoneTitle: 'Lihavoitu 60:stä: riittää torniin',
    metalTitle: 'Lihavoitu 30:stä: riittää vaunun parannukseen',
    foodCountTitle: 'Lihavoitu, kun varasto linnan ja farmien tuoton kanssa ei riitä kaikille yksiköille täyteen ateriaan',
    foodStoreTitle: 'Varaston enimmäismäärä',
    nothingSelected: 'Mitään ei ole valittu',
    minimapLabel: 'Koko kentän kartta: paina tai vedä sitä katsoaksesi sinne',
    castle: 'Linna',
    lair: 'Pesä',
    ghoul: 'Ghouli',
    ogre: 'Ogri',
    raider: 'Rosvo',
    graded: '{name} (taso {n})',
    atHome: '{n}/{max} kotona',
    nextUnit: 'seuraava yksikkö {done}',
    crewLine: 'ryhmä {n}/{max}',
    levelLine: 'taso {n}',
    upgrading: 'parannus {done}',
    goingUp: 'rakenteilla {done}',
    dugOut: 'tyhjä',
    depthLine: 'syvyys {n}/{max}, {stone}',
    nextFood: 'ruoka {done}',
    attacking: 'kohde: {name}',
    hpLine: 'Kestävyys {hp}/{max}',
    crewNewTitle: 'Uusi: {name}',
    crewOfTitle: 'Ryhmä: {name}',
    crewHintNew: 'Enintään {n}; kotona olevista parhaat tähän työhön on valittu.',
    crewHintBand: 'Enintään {n}; kotona olevista parhaat taistelijat on valittu.',
    crewHint: 'Enintään {n}. Valitsemattomat kotiin, valitut tänne.',
    order: 'Järjestys',
    sortDefault: 'Oletus',
    sortDefaultTitle: 'Ensin valitut, sitten kotona olevat, työssä parhaat ensin',
    sortHero: 'Sankari',
    sortHeroTitle: 'Ensin sankarit, jotka nousevat tasoissa nopeammin; sitten korkein taso',
    sortLevel: 'Taso',
    sortLevelTitle: 'Korkein taso ensin',
    sortNear: 'Lähimmät',
    sortNearTitle: 'Rakennusta lähimmät ensin',
    sortSkillTitle: 'Parhaat ensin: {skill}',
    sortAttack: 'Hyökkäys',
    crewCount: '{n}/{max}',
    cancel: 'Peruuta',
    send: 'Lähetä',
    okTitle: '{action} (Enter tai {key})',
    heroTitle: 'Sankari: nousee tasoissa muita nopeammin',
    skillRanged: 'Ampuminen',
    skillMelee: 'Lähitaistelu',
    skillBuild: 'Rakentaminen',
    skillFarming: 'Viljely',
    skillBreeding: 'Lisääntyminen',
    skillRunning: 'Juoksu',
    whereOutside: 'ulkona',
    whereHere: 'täällä',
    whereComing: 'tulossa tänne',
    whereHome: 'kotona',
    whereGoingHome: 'menossa kotiin',
    whereIn: '{name}',
    whereTo: '→ {name}',
    diedHunger: 'kuoli nälkään',
    diedCombat: 'kaatui taistelussa',
    heroesHeading: 'Sankarit',
    heroesHint: 'Korkein taso ensin, sitten kaatuneet. {skills}',
    heroesCount: { one: '{n} sankari {total}:sta', other: '{n} sankaria {total}:sta' },
    fallenCount: { one: '{n} kaatunut', other: '{n} kaatunutta' },
    heroesNoneAlive: 'Ei eläviä.',
    heroesNoneYet: 'Ei vielä: noin joka kymmenes syntyy sankariksi.',
    close: 'Sulje',
    scoresGameOver: 'Peli päättyi',
    scoresYouWon: 'Voitit',
    scoresYouLost: 'Hävisit',
    scoresNobody: '{time} · ei voittajaa',
    scoresWon: '{time} · voittaja: {sides}',
    quickWinNote: 'nopea voitto: pisteet ×{times}',
    scoresSide: 'Puoli',
    scoresTotal: 'Yhteensä',
    scoresBonus: 'Bonus',
    scoresBonusTitle: 'Nopea voitto: voittajien pisteet kerrotaan, {ranges}',
    quickWinRange: '×{times}, kun {from}–{to} minuuttia',
    scoreWon: 'Voitto',
    scoreWonWhat: 'voittajajoukkueelle',
    scoreCastles: 'Linnat',
    scoreCastlesWhat: 'kaadetut vihollislinnat ja -pesät',
    scoreFelled: 'Kaadettu',
    scoreFelledWhat: 'kaadetut vihollisrakennukset',
    scoreKills: 'Tapot',
    scoreKillsWhat: 'tapetut vihollisyksiköt',
    scoreDamage: 'Vahinko',
    scoreDamageWhat: 'vihollisrakennuksilta viety kestävyys',
    scoreUpgrades: 'Parannukset',
    scoreUpgradesWhat: 'parannuksilla saavutetut tasot',
    scoreBuilt: 'Rakennettu',
    scoreBuiltWhat: 'valmiit rakennukset',
    scoreBorn: 'Syntyneet',
    scoreBornWhat: 'syntyneet',
    scoreStone: 'Kivi',
    scoreStoneWhat: 'kaivettu kivi',
    scoreFood: 'Ruoka',
    scoreFoodWhat: 'ryhmien kasvattama ruoka',
    pointsEach: { one: '{n} piste kustakin', other: '{n} pistettä kustakin' },
    pointPer: 'piste per {n}',
    keepWatching: 'Jatka katsomista',
    leaveMatch: 'Poistu ottelusta',
    // As in Russian: the English key where the word has it (T, P, F), else
    // the first letter, else a free one (H**y**ökkää: H is Heroes'). Finnish
    // keyboards have the English letters on the same keys.
    keyTower: 'T',
    keyWagon: 'V',
    keyPit: 'P',
    keyFarm: 'F',
    keyBand: 'J',
    keyUpgrade: 'K',
    keyCrew: 'R',
    keyHeroes: 'S',
    keyAttack: 'Y',
  },
};

/** @typedef {keyof typeof WORDS.en} Word */
/** @typedef {{ word: Word, values?: Record<string, string | number> }} Said A text to show, and what fills it in. */

/**
 * A text with its `{placeholders}` filled in; one with no value stays as it is.
 * @param {string} text
 * @param {Record<string, string | number>} [values]
 */
export function fill(text, values = {}) {
  return text.replace(/\{(\w+)\}/g, (all, key) => (Object.hasOwn(values, key) ? String(values[key]) : all));
}

/**
 * A text in a language; for a word with plural forms, the one for `{n}`.
 * @param {import('./language.js').PageLanguage} language
 * @param {Said} said
 */
export function say(language, { word, values = {} }) {
  const entry = /** @type {string | Record<string, string>} */ (WORDS[language][word]);
  const text = typeof entry === 'string' ? entry : entry[new Intl.PluralRules(language).select(Number(values.n))] ?? entry.other;
  return fill(text, values);
}

/**
 * Whether a text, such as a mode's key from the server, is one of the words.
 * @param {unknown} key
 * @returns {key is Word}
 */
export const isWord = (key) => typeof key === 'string' && Object.hasOwn(WORDS.en, key);

/**
 * Put every element under `root` that names its words in a language: its
 * text (`data-word`), tooltip (`data-word-title`) and label for screen
 * readers (`data-word-label`).
 * @param {ParentNode} root
 * @param {import('./language.js').PageLanguage} language
 */
export function translate(root, language) {
  const word = (/** @type {string | undefined} */ key) => say(language, { word: /** @type {Word} */ (key) });
  for (const element of /** @type {NodeListOf<HTMLElement>} */ (root.querySelectorAll('[data-word]'))) {
    element.textContent = word(element.dataset.word);
  }
  for (const element of /** @type {NodeListOf<HTMLElement>} */ (root.querySelectorAll('[data-word-title]'))) {
    element.title = word(element.dataset.wordTitle);
  }
  for (const element of /** @type {NodeListOf<HTMLElement>} */ (root.querySelectorAll('[data-word-label]'))) {
    element.setAttribute('aria-label', word(element.dataset.wordLabel));
  }
}
